openapi: 3.0.0
info:
  version: "1.0.0"
  title: Trading LTD
  description: trading platform
  contact:
    email: honguttdc+swaggerhub@bcit.ca
tags:
  - name: admin
    description: manage the platform
  - name: customer
    description: trading stock and manage portfolio
paths:
  /stats:
    get:
      tags:
        - devices
      summary: gets account data readings
      operationId: app.get_stats
      description: Get account data from STORAGE after a timestamp
      responses:
        '200':
          description: Successful return list of account data from STORAGE
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Stats'
        '400':
          description: Invalid request from STORAGE
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Stats:
      required:
        - num_account
        - num_trade
        - total_cash
        - total_value
        - total_share
      properties:
        num_account:
          type: integer
          example: 5
        num_trade:
          type: integer
          example: 50
        total_cash:
          type: integer
          example: 55
        total_value:
          type: integer
          example: 1000
        total_share:
          type: integer
          example: 2222