FROM ubuntu

RUN apt update && apt install -y python3 python3-pip

WORKDIR /app
COPY ./requirements.txt /app/

RUN pip3 install -r requirements.txt

COPY . /app/

ENTRYPOINT [ "python3" ]
CMD [ "app.py" ]